COLUMNS:
  city: string
  match_type: string
  target_runs: int
  batting_team: string
  bowling_team: string
  current_score: int
  wickets: int
  crr: float
  rrr: float
  batter_total_runs: int
  batter_strikerate: float
  non_striker_runs: int
  non_striker_strikerate: float
  batting_team_win: bool

TARGET_COLUMN: batting_team_win

Categorial_COLUMNS:
  - city
  - match_type
  - batting_team
  - bowling_team

Numerical_COLUMNS:
  - target_runs
  - current_score
  - wickets
  - crr
  - rrr
  - batter_total_runs
  - batter_strikerate
  - non_striker_runs
  - non_striker_strikerate
