COLUMNS:

  id: int
  season: int
  city: str
  date: str
  match_type: str
  player_of_match: str
  venue: str
  team1: str
  team2: str
  toss_winner: str
  toss_decision: str
  winner: str
  result: str
  result_margin: int
  target_runs: int
  target_overs: int
  super_over: int
  method: str
  umpire1: str
  umpire2: str
  match_id: int
  inning: int
  batting_team: str
  bowling_team: str
  over: int
  ball: int
  batter: str
  bowler: str
  non_striker: str
  batsman_runs: int
  extra_runs: int
  total_runs: int
  extras_type: str
  is_wicket: int
  player_dismissed: str
  dismissal_kind: str
  fielder: str
  runs_left: int
  balls_left: int
  wickets: int
  total_runs_x: int
  current_rate: float
  required_rate: float
  result: str

TARGET_COLUMN: result
