COLUMNS:
  city: string
  match_type: string
  target_runs: int
  batting_team: string
  bowling_team: string
  current_score: int
  wickets: int
  crr: float
  rrr: float
  batter_total_runs: int
  batter_strikerate: float
  non_striker_runs: int
  non_striker_strikerate: float
  batting_team_win: bool

TARGET_COLUMN: batting_team_win
