artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/suyashambule/dates/3084b0c3eaf0a6fd0249961750bbec5444e5cee5/IPL_Prediction%20file.zip
  unzip_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/IPL_Prediction%20file.zip

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/IPL_Prediction file/output.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_splitter:
  root_dir: artifacts/data_splitting
  train_data: artifacts/data_splitting/train.csv
  test_data: artifacts/data_splitting/test.csv
  unzip_data_dir: artifacts/data_ingestion/IPL_Prediction file/output.csv
  split_ratio: 0.2
  random_state: 42
